export const timezones = [
  { label: 'Eastern Time (ET)', value: 'America/New_York' },
  { label: 'Central Time (CT)', value: 'America/Chicago' },
  { label: 'Mountain Time (MT)', value: 'America/Denver' },
  { label: 'Pacific Time (PT)', value: 'America/Los_Angeles' },
  { label: 'Alaska Time (AKT)', value: 'America/Anchorage' },
  { label: 'Hawaii-Aleutian Time (HST)', value: 'Pacific/Honolulu' },
  { label: 'GMT', value: 'Europe/London' },
  { label: 'Central European Time (CET)', value: 'Europe/Berlin' },
  { label: 'Eastern European Time (EET)', value: 'Europe/Athens' },
  { label: 'Moscow Standard Time (MSK)', value: 'Europe/Moscow' },
  { label: 'UAE Standard Time (GST)', value: 'Asia/Dubai' },
  { label: 'India Standard Time (IST)', value: 'Asia/Kolkata' },
  { label: 'Bangkok Standard Time (ICT)', value: 'Asia/Bangkok' },
  { label: 'China Standard Time (CST)', value: 'Asia/Shanghai' },
  { label: 'Japan Standard Time (JST)', value: 'Asia/Tokyo' },
  { label: 'Korea Standard Time (KST)', value: 'Asia/Seoul' },
  { label: 'Australia Eastern Time (AEST)', value: 'Australia/Sydney' },
  { label: 'Australia Central Time (ACST)', value: 'Australia/Adelaide' },
  { label: 'Australia Western Time (AWST)', value: 'Australia/Perth' },
  { label: 'New Zealand Time (NZST)', value: 'Pacific/Auckland' },
  { label: 'Fiji Standard Time (FJT)', value: 'Pacific/Fiji' },
  { label: 'UTC', value: 'UTC' },
];
